// Copyright Gleb Obitotsky <glebobitotsky@yandex.com> 2026.
//
// The code is distributed under the Mozilla Public License Version 2.0 license
// (you can find the license file in the root folder).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: packet.proto

package packet

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketType int32

const (
	PacketType_UNKNOWN       PacketType = 0
	PacketType_PING_REQUEST  PacketType = 1
	PacketType_PING_RESPONSE PacketType = 2
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PING_REQUEST",
		2: "PING_RESPONSE",
	}
	PacketType_value = map[string]int32{
		"UNKNOWN":       0,
		"PING_REQUEST":  1,
		"PING_RESPONSE": 2,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_packet_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_packet_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{0}
}

type MeshPing struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             PacketType             `protobuf:"varint,1,opt,name=type,proto3,enum=packet.PacketType" json:"type,omitempty"`
	Seq              uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	ClientId         []byte                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Battery          uint32                 `protobuf:"varint,4,opt,name=battery,proto3" json:"battery,omitempty"`
	CpuUsage         float32                `protobuf:"fixed32,5,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	ReceivedByTarget uint32                 `protobuf:"varint,6,opt,name=received_by_target,json=receivedByTarget,proto3" json:"received_by_target,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MeshPing) Reset() {
	*x = MeshPing{}
	mi := &file_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshPing) ProtoMessage() {}

func (x *MeshPing) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshPing.ProtoReflect.Descriptor instead.
func (*MeshPing) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{0}
}

func (x *MeshPing) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_UNKNOWN
}

func (x *MeshPing) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MeshPing) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *MeshPing) GetBattery() uint32 {
	if x != nil {
		return x.Battery
	}
	return 0
}

func (x *MeshPing) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MeshPing) GetReceivedByTarget() uint32 {
	if x != nil {
		return x.ReceivedByTarget
	}
	return 0
}

var File_packet_proto protoreflect.FileDescriptor

const file_packet_proto_rawDesc = "" +
	"\n" +
	"\fpacket.proto\x12\x06packet\"\xc6\x01\n" +
	"\bMeshPing\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.packet.PacketTypeR\x04type\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\fR\bclientId\x12\x18\n" +
	"\abattery\x18\x04 \x01(\rR\abattery\x12\x1b\n" +
	"\tcpu_usage\x18\x05 \x01(\x02R\bcpuUsage\x12,\n" +
	"\x12received_by_target\x18\x06 \x01(\rR\x10receivedByTarget*>\n" +
	"\n" +
	"PacketType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fPING_REQUEST\x10\x01\x12\x11\n" +
	"\rPING_RESPONSE\x10\x02B\n" +
	"Z\b./packetb\x06proto3"

var (
	file_packet_proto_rawDescOnce sync.Once
	file_packet_proto_rawDescData []byte
)

func file_packet_proto_rawDescGZIP() []byte {
	file_packet_proto_rawDescOnce.Do(func() {
		file_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_proto_rawDesc), len(file_packet_proto_rawDesc)))
	})
	return file_packet_proto_rawDescData
}

var file_packet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_proto_goTypes = []any{
	(PacketType)(0),  // 0: packet.PacketType
	(*MeshPing)(nil), // 1: packet.MeshPing
}
var file_packet_proto_depIdxs = []int32{
	0, // 0: packet.MeshPing.type:type_name -> packet.PacketType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_packet_proto_init() }
func file_packet_proto_init() {
	if File_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_proto_rawDesc), len(file_packet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_proto_goTypes,
		DependencyIndexes: file_packet_proto_depIdxs,
		EnumInfos:         file_packet_proto_enumTypes,
		MessageInfos:      file_packet_proto_msgTypes,
	}.Build()
	File_packet_proto = out.File
	file_packet_proto_goTypes = nil
	file_packet_proto_depIdxs = nil
}
